FROM python:3.11-slim

# Definir pasta de trabalho
WORKDIR /app

# Instalar dependências essenciais do sistema
RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*

# Copiar requirements e instalar pacotes Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código do bot
COPY arbitrage_bot.py .

# Criar pasta /data que será usada para o volume do banco e chave
RUN mkdir -p /app/data
ENV DATA_DIR="/app/data"

# Expor a porta do WebSocket
EXPOSE 8765

# Iniciar motor
CMD ["python", "arbitrage_bot.py"]
