# Etapa 1: Build

FROM node:22-alpine AS build
WORKDIR /app

# Copiar os arquivos de dependência e instalar
COPY package.json package-lock.json* ./
RUN npm install

# Copiar todo o código fonte
COPY . .

# Receber a variável de ambiente VITE_WS_URL no momento do build no Easypanel
ARG VITE_WS_URL
ENV VITE_WS_URL=$VITE_WS_URL

# Executar o build otimizado (cria a pasta /dist)
RUN npm run build

# Etapa 2: Servidor Web de Produção (Nginx)
FROM nginx:alpine

# Copiar o config do nginx customizado
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar os arquivos gerados no build para o Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Expor porta 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
